version: '{branch}-{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk11
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

install:
  - cmd: set EXIST_HOME=%APPVEYOR_BUILD_FOLDER%
  - sh: export EXIST_HOME=$APPVEYOR_BUILD_FOLDER

build_script:
  - cmd: build.bat
  - sh: cd $EXIST_HOME && ./build.sh clean && ./build.sh

test_script:
  - cmd: build.bat -Dexist.autodeploy=off -Dtest.haltonerror=true -Dtest.haltonfailure=true test
  - sh:  cd $EXIST_HOME && ./build.sh -Dexist.autodeploy=off -Dtest.haltonerror=true -Dtest.haltonfailure=true test

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      foreach ($file in Get-ChildItem -Path "$($env:APPVEYOR_BUILD_FOLDER)\exist-core\target\junit-reports\data\" -Filter *.xml) {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $file.FullName)
      }

on_failure:
  - cmd: 7z a junit-failed-data.zip %APPVEYOR_BUILD_FOLDER%\exist-core\target\junit-reports\data\ && appveyor PushArtifact junit-failed-data.zip
  - sh: tar czvf junit-failed-data.tgz $APPVEYOR_BUILD_FOLDER/exist-core/target/junit-reports/data/ && appveyor PushArtifact junit-failed-data.tgz

artifacts:
  - path: exist-core\target\junit-reports
    name: junit-reports
